### ISSUE TITLE
Broken SSL_write signature

### ISSUE THREAD

**Issue by DarkPointer** [NytroRST/NetRipper#10]
Hi,
I have noticed that the latest chrome release (Version 62.0.3202.62 (Official Build) (64-bit)) broke the SSL_write signature in NetRipper.

This was the oldsig for SSL_write `0x48, 0x89, 0x5C, 0x24, 0x08, 0x48, 0x89, 0x6C, 0x24, 0x10, 0x48, 0x89, 0x74, 0x24, 0x18, 0x57, 0x41, 0x56, 0x41, 0x57, 0x48, 0x83, 0xEC, 0x30, 0x83, 0x22, 0x00, 0x4D, 0x8B, 0xF8, 0x48, 0x8B, 0x41, 0x48`

and this is the new one `0x48, 0x89, 0x5C, 0x24, 0x08, 0x48, 0x89, 0x6C, 0x24, 0x10, 0x48, 0x89, 0x74, 0x24, 0x18, 0x57, 0x41, 0x56, 0x41, 0x57, 0x48, 0x83, 0xEC, 0x30, 0x83, 0x22, 0x00, 0x4D, 0x8B, 0xF8, 0x48, 0x8B, 0x41, 0x38`

The change was only the last byte of the sig.

It has come to my notice that the SSL_read sig is broken too now, but I didn't have the time at the moment to find the new sig and do a full pull request. So I thought to mention the changes and the new sig of SSL_write.

Thanks.

**Comment by NytroRST** [comment]
Hi, thank you for the information, I fixed it with the last commit.
