### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by drlogin** [NytroRST/NetRipper#12]
i got following error when trying compile DLL
1>------ Build started: Project: DLL, Configuration: Release Win32 ------
1>Project file contains ToolsVersion="15.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>  InjectedDLL.cpp
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(26): error C2146: syntax error : missing ';' before identifier 'dwStartAddress'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(26): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(34): error C2146: syntax error : missing ';' before identifier 'dwAddress'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(34): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(35): error C2146: syntax error : missing ';' before identifier 'dwPointerOfAddress'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(35): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(47): error C2146: syntax error : missing ';' before identifier 'SearchMemory'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(47): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(47): warning C4183: 'SearchMemory': missing return type; assumed to be a member function returning 'int'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(48): error C2146: syntax error : missing ';' before identifier 'SearchMemoryByN'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(48): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(48): error C2086: 'int Process::uint32_t' : redefinition
1>          g:\coding job\netripper-master\netripper-master\dll\Process.h(47) : see declaration of 'Process::uint32_t'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(48): warning C4183: 'SearchMemoryByN': missing return type; assumed to be a member function returning 'int'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(49): error C2146: syntax error : missing ';' before identifier 'SearchSignature'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(49): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(49): error C2086: 'int Process::uint32_t' : redefinition
1>          g:\coding job\netripper-master\netripper-master\dll\Process.h(47) : see declaration of 'Process::uint32_t'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(49): warning C4183: 'SearchSignature': missing return type; assumed to be a member function returning 'int'
1>InjectedDLL.cpp(98): error C2102: '&' requires l-value
1>InjectedDLL.cpp(99): error C2102: '&' requires l-value
1>InjectedDLL.cpp(106): error C2102: '&' requires l-value
1>InjectedDLL.cpp(107): error C2102: '&' requires l-value
1>InjectedDLL.cpp(117): error C2102: '&' requires l-value
1>InjectedDLL.cpp(118): error C2102: '&' requires l-value
1>InjectedDLL.cpp(128): error C2102: '&' requires l-value
1>InjectedDLL.cpp(129): error C2102: '&' requires l-value
1>InjectedDLL.cpp(134): error C2102: '&' requires l-value
1>InjectedDLL.cpp(135): error C2102: '&' requires l-value
1>InjectedDLL.cpp(145): error C2102: '&' requires l-value
1>InjectedDLL.cpp(146): error C2102: '&' requires l-value
1>InjectedDLL.cpp(183): error C2102: '&' requires l-value
1>  NonExportedHooks.cpp
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(26): error C2146: syntax error : missing ';' before identifier 'dwStartAddress'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(26): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(34): error C2146: syntax error : missing ';' before identifier 'dwAddress'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(34): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(35): error C2146: syntax error : missing ';' before identifier 'dwPointerOfAddress'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(35): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(47): error C2146: syntax error : missing ';' before identifier 'SearchMemory'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(47): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(47): warning C4183: 'SearchMemory': missing return type; assumed to be a member function returning 'int'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(48): error C2146: syntax error : missing ';' before identifier 'SearchMemoryByN'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(48): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(48): error C2086: 'int Process::uint32_t' : redefinition
1>          g:\coding job\netripper-master\netripper-master\dll\Process.h(47) : see declaration of 'Process::uint32_t'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(48): warning C4183: 'SearchMemoryByN': missing return type; assumed to be a member function returning 'int'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(49): error C2146: syntax error : missing ';' before identifier 'SearchSignature'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(49): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(49): error C2086: 'int Process::uint32_t' : redefinition
1>          g:\coding job\netripper-master\netripper-master\dll\Process.h(47) : see declaration of 'Process::uint32_t'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(49): warning C4183: 'SearchSignature': missing return type; assumed to be a member function returning 'int'
1>NonExportedHooks.cpp(9): error C2078: too many initializers
1>NonExportedHooks.cpp(10): error C2078: too many initializers
1>NonExportedHooks.cpp(27): error C2039: 'dwStartAddress' : is not a member of 'SECTION_INFO'
1>          g:\coding job\netripper-master\netripper-master\dll\Process.h(25) : see declaration of 'SECTION_INFO'
1>NonExportedHooks.cpp(35): error C2065: 'uint32_t' : undeclared identifier
1>NonExportedHooks.cpp(35): error C2146: syntax error : missing ';' before identifier 'pWrite'
1>NonExportedHooks.cpp(35): error C2065: 'pWrite' : undeclared identifier
1>NonExportedHooks.cpp(35): error C2039: 'dwStartAddress' : is not a member of 'SECTION_INFO'
1>          g:\coding job\netripper-master\netripper-master\dll\Process.h(25) : see declaration of 'SECTION_INFO'
1>NonExportedHooks.cpp(36): error C2065: 'uint32_t' : undeclared identifier
1>NonExportedHooks.cpp(36): error C2146: syntax error : missing ';' before identifier 'pRead'
1>NonExportedHooks.cpp(36): error C2065: 'pRead' : undeclared identifier
1>NonExportedHooks.cpp(36): error C2039: 'dwStartAddress' : is not a member of 'SECTION_INFO'
1>          g:\coding job\netripper-master\netripper-master\dll\Process.h(25) : see declaration of 'SECTION_INFO'
1>NonExportedHooks.cpp(38): error C2065: 'pWrite' : undeclared identifier
1>NonExportedHooks.cpp(38): error C2065: 'pRead' : undeclared identifier
1>NonExportedHooks.cpp(46): error C2065: 'pWrite' : undeclared identifier
1>NonExportedHooks.cpp(47): error C2065: 'pRead' : undeclared identifier
1>NonExportedHooks.cpp(49): error C2065: 'pWrite' : undeclared identifier
1>NonExportedHooks.cpp(49): error C2102: '&' requires l-value
1>NonExportedHooks.cpp(50): error C2065: 'pRead' : undeclared identifier
1>NonExportedHooks.cpp(50): error C2102: '&' requires l-value
1>NonExportedHooks.cpp(57): error C2078: too many initializers
1>NonExportedHooks.cpp(67): error C2039: 'dwStartAddress' : is not a member of 'SECTION_INFO'
1>          g:\coding job\netripper-master\netripper-master\dll\Process.h(25) : see declaration of 'SECTION_INFO'
1>NonExportedHooks.cpp(75): error C2065: 'uint32_t' : undeclared identifier
1>NonExportedHooks.cpp(75): error C2146: syntax error : missing ';' before identifier 'pSend'
1>NonExportedHooks.cpp(75): error C2065: 'pSend' : undeclared identifier
1>NonExportedHooks.cpp(75): error C2039: 'dwStartAddress' : is not a member of 'SECTION_INFO'
1>          g:\coding job\netripper-master\netripper-master\dll\Process.h(25) : see declaration of 'SECTION_INFO'
1>NonExportedHooks.cpp(76): error C2065: 'uint32_t' : undeclared identifier
1>NonExportedHooks.cpp(76): error C2146: syntax error : missing ';' before identifier 'pRecv'
1>NonExportedHooks.cpp(76): error C2065: 'pRecv' : undeclared identifier
1>NonExportedHooks.cpp(76): error C2039: 'dwStartAddress' : is not a member of 'SECTION_INFO'
1>          g:\coding job\netripper-master\netripper-master\dll\Process.h(25) : see declaration of 'SECTION_INFO'
1>NonExportedHooks.cpp(78): error C2065: 'pSend' : undeclared identifier
1>NonExportedHooks.cpp(78): error C2065: 'pRecv' : undeclared identifier
1>NonExportedHooks.cpp(86): error C2065: 'pSend' : undeclared identifier
1>NonExportedHooks.cpp(87): error C2065: 'pRecv' : undeclared identifier
1>NonExportedHooks.cpp(89): error C2065: 'pSend' : undeclared identifier
1>NonExportedHooks.cpp(90): error C2065: 'pRecv' : undeclared identifier
1>NonExportedHooks.cpp(97): error C2078: too many initializers
1>NonExportedHooks.cpp(105): error C2039: 'dwStartAddress' : is not a member of 'SECTION_INFO'
1>          g:\coding job\netripper-master\netripper-master\dll\Process.h(25) : see declaration of 'SECTION_INFO'
1>NonExportedHooks.cpp(113): error C2065: 'uint32_t' : undeclared identifier
1>NonExportedHooks.cpp(113): error C2146: syntax error : missing ';' before identifier 'pSend'
1>NonExportedHooks.cpp(113): error C2065: 'pSend' : undeclared identifier
1>NonExportedHooks.cpp(113): error C2039: 'dwStartAddress' : is not a member of 'SECTION_INFO'
1>          g:\coding job\netripper-master\netripper-master\dll\Process.h(25) : see declaration of 'SECTION_INFO'
1>NonExportedHooks.cpp(114): error C2065: 'uint32_t' : undeclared identifier
1>NonExportedHooks.cpp(114): error C2146: syntax error : missing ';' before identifier 'pRecv'
1>NonExportedHooks.cpp(114): error C2065: 'pRecv' : undeclared identifier
1>NonExportedHooks.cpp(114): error C2039: 'dwStartAddress' : is not a member of 'SECTION_INFO'
1>          g:\coding job\netripper-master\netripper-master\dll\Process.h(25) : see declaration of 'SECTION_INFO'
1>NonExportedHooks.cpp(116): error C2065: 'pSend' : undeclared identifier
1>NonExportedHooks.cpp(116): error C2065: 'pRecv' : undeclared identifier
1>NonExportedHooks.cpp(124): error C2065: 'pSend' : undeclared identifier
1>NonExportedHooks.cpp(125): error C2065: 'pRecv' : undeclared identifier
1>NonExportedHooks.cpp(127): error C2065: 'pSend' : undeclared identifier
1>NonExportedHooks.cpp(128): error C2065: 'pRecv' : undeclared identifier
1>  Process.cpp
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(26): error C2146: syntax error : missing ';' before identifier 'dwStartAddress'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(26): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(34): error C2146: syntax error : missing ';' before identifier 'dwAddress'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(34): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(35): error C2146: syntax error : missing ';' before identifier 'dwPointerOfAddress'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(35): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(47): error C2146: syntax error : missing ';' before identifier 'SearchMemory'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(47): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(47): warning C4183: 'SearchMemory': missing return type; assumed to be a member function returning 'int'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(48): error C2146: syntax error : missing ';' before identifier 'SearchMemoryByN'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(48): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(48): error C2086: 'int Process::uint32_t' : redefinition
1>          g:\coding job\netripper-master\netripper-master\dll\Process.h(47) : see declaration of 'Process::uint32_t'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(48): warning C4183: 'SearchMemoryByN': missing return type; assumed to be a member function returning 'int'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(49): error C2146: syntax error : missing ';' before identifier 'SearchSignature'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(49): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(49): error C2086: 'int Process::uint32_t' : redefinition
1>          g:\coding job\netripper-master\netripper-master\dll\Process.h(47) : see declaration of 'Process::uint32_t'
1>g:\coding job\netripper-master\netripper-master\dll\Process.h(49): warning C4183: 'SearchSignature': missing return type; assumed to be a member function returning 'int'
1>Process.cpp(7): error C2143: syntax error : missing ';' before 'Process::SearchMemory'
1>Process.cpp(7): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>Process.cpp(8): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>Process.cpp(15): error C2064: term does not evaluate to a function taking 1 arguments
1>Process.cpp(26): error C2143: syntax error : missing ';' before 'Process::SearchMemoryByN'
1>Process.cpp(26): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>Process.cpp(26): error C2086: 'int uint32_t' : redefinition
1>          Process.cpp(7) : see declaration of 'uint32_t'
1>Process.cpp(27): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>Process.cpp(38): error C2064: term does not evaluate to a function taking 1 arguments
1>Process.cpp(49): error C2143: syntax error : missing ';' before 'Process::SearchSignature'
1>Process.cpp(49): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>Process.cpp(49): error C2086: 'int uint32_t' : redefinition
1>          Process.cpp(7) : see declaration of 'uint32_t'
1>Process.cpp(50): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>Process.cpp(51): error C2146: syntax error : missing ';' before identifier 'dwMax'
1>Process.cpp(51): error C2065: 'dwMax' : undeclared identifier
1>Process.cpp(51): error C2146: syntax error : missing ';' before identifier 'p_pvStartAddress'
1>Process.cpp(51): error C2036: 'void *' : unknown size
1>Process.cpp(51): warning C4552: '+' : operator has no effect; expected operator with side-effect
1>Process.cpp(63): error C2146: syntax error : missing ')' before identifier 'p_pvStartAddress'
1>Process.cpp(63): error C2059: syntax error : ')'
1>Process.cpp(64): error C2146: syntax error : missing ')' before identifier 'p_pvBuffer'
1>Process.cpp(64): error C2059: syntax error : ')'
1>Process.cpp(82): error C2146: syntax error : missing ';' before identifier 'p_pvStartAddress'
1>Process.cpp(82): error C2036: 'void *' : unknown size
1>Process.cpp(82): warning C4552: '+' : operator has no effect; expected operator with side-effect
1>Process.cpp(94): error C2078: too many initializers
1>Process.cpp(127): error C2146: syntax error : missing ')' before identifier 'hModule'
1>Process.cpp(127): error C2059: syntax error : ')'
1>Process.cpp(141): error C2146: syntax error : missing ')' before identifier 'hModule'
1>Process.cpp(142): error C2059: syntax error : ')'
1>Process.cpp(151): error C2039: 'dwStartAddress' : is not a member of 'SECTION_INFO'
1>          g:\coding job\netripper-master\netripper-master\dll\Process.h(25) : see declaration of 'SECTION_INFO'
1>Process.cpp(151): error C2146: syntax error : missing ';' before identifier 'hModule'
1>Process.cpp(151): warning C4552: '+' : operator has no effect; expected operator with side-effect
1>  Generating Code...
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by DarkPointer** [comment]
Have you tried to retarget the solution ? you can do this by going into solution properties and under general you will find the Target platform version and the platform toolset, modify the values according to your installed ones and try to compile.

**Comment by NytroRST** [comment]
Which version of Visual Studio do you use? Did you try Visual Studio 2015?
You should try DarkPointer's suggestion, it should work.

**Comment by drlogin** [comment]
i used 2015  but not DarkPointer's

**Comment by drlogin** [comment]
(Have you tried to retarget the solution ? you can do this by going into solution properties and under general you will find the Target platform version and the platform toolset, modify the values according to your installed ones and try to compile.) i did that not work too

**Comment by NytroRST** [comment]
I think you should use Visual Studio Community 2017. It should have the MSBUILD (Toolset) version 15.
This should work.
