### ISSUE TITLE
Not works in chrome 62 32bit

### ISSUE THREAD

**Issue by BemJam** [NytroRST/NetRipper#13]
Hello i encouter this problem ,when i using chrome 62 32bit 

Problem is :
SearchSignature did not find the signature!

**Comment by NytroRST** [comment]
I know, but is it Chrome still used on 32bit? 
If there are many users of Chrome on 32bit, I will likely add a signature for 32bit as well.

**Comment by BemJam** [comment]
I am using 32bit , my friends too!

**Comment by ilovejiang** [comment]
here lists another question : the lastest version NetRipper , using in firefox (32bits version) can reflectiveInject successfully , but can not be initialized . The default path doesn't contain the "NetRipper" file .

**Comment by Ianwang2011** [comment]
I got the same issure, i have search the signature with ollydbg2.0, it still cannot find the signature. It seam that the signature do now work in 32bit.

@NytroRST

**Comment by NytroRST** [comment]
Fixed, it should work on Chrome 64 - 32 bits.
