### ISSUE TITLE
Does not work on Firefox

### ISSUE THREAD

**Issue by ilovejiang** [NytroRST/NetRipper#15]
Hi All
   If there is anyone joined into this great project (lots thanks to @NytroRST ),PLEASE I NEED HELP NOW!
   When using NetRipper (the lastest version pushed in Nov.) hooking FireFox 57.0.0 32bit (i do that in both win32 & win64) , I meet a problem which CMD tells "Successfully Rejected in process xxxx" ,but in the default path "TEMP" , i can not find the "NetRipperLog.txt" file . Is it means the hooking process doesn't initialise ? 
   So Confused this makes me !! Need Help !!
   Why this happens ? Only on me ? If you guys also meet the same problem or already find the solution/answer , PLEASE CONNECT ! 
   Before i get crazy .....ORZ

**Comment by NytroRST** [comment]
Added a new option to NetRipper.exe: "--noreflective".
Using this option, it should work to inject the DLL into Firefox.
I will continue looking to find the issue with reflective injection.
