### ISSUE TITLE
the chrome signature is wrong

### ISSUE THREAD

**Issue by adevelopcr** [NytroRST/NetRipper#21]
the chrome SSL_write signature is wrong so I had to make a signature manually I tested my signature and it worked on 60 , 64 , two 67 versions
but I doubt it will continue work for the coming versions
isn't there any reliable way that isn't affected by chrome updates ?
and if I know a function SSL_write calls (not directly but it calls function that calls another ..... finally calls this function) can I obtain the address of SSL_write from a stack trace ?

**Comment by adevelopcr** [comment]
I checked chrome 62.0.3202.62 and downloaded the pdb for chrome dll and I typed in dbh : 

load chrome.dll.pdb
name SSL_write

and the surprising thing is that I got : no symbol found
I tried with SSL_read and had the same result
how did this happened ? did they remove it from chrom 62 ?

**Comment by NytroRST** [comment]
The latest version should work on latest versions of Chrome (both 32 bits and 64 bits).
Until the last version, I placed the "line number" in the signature and it was changed with each release. Right now, it should be pretty stable.

**Comment by adevelopcr** [comment]
the problem is that chrome changes the start of the function during runtime
I got the signature in two ways : 
1 - with ida pro
2 - loaded chrome.dll inside a console application and dumped some bytes from the start of the function
the signature was the same as yours
but in inside chrome I dumped some bytes from the start of the function and found that chrome replaces the first some bytes with a jump to a relative address which changes from version to another
I had to get around this
but the pain now us that I can't find SSL_write in chrome 62 and 63 even with pdb files

**Comment by NytroRST** [comment]
"found that chrome replaces the first some bytes with a jump to a relative address" -> Do you mean the first bytes of the SSL_Read/Write functions are changed to a jump? If so, this does NetRipper. Or some other tool that hooks the functions.
If it does not work with symbols, use this: https://nytrosecurity.com/2018/02/26/hooking-chromes-ssl-functions/
However, related to NetRipper itself, does it work with latest version of Chrome?

**Comment by adevelopcr** [comment]
the jump was to some function in chrome in the namespace bss

**Comment by NytroRST** [comment]
I have no idea, it did not happen for me and it worked with Chrome latest version.
