### ISSUE TITLE
Chrome 72_x64 Version  not call SSL_Write?

### ISSUE THREAD

**Issue by qiushifengyu** [NytroRST/NetRipper#26]
Chrome 72_x64 Version  not call SSL_Write? I use windbg debug it can't break here

**Comment by NytroRST** [comment]
I also did a test right now and it did not break in SSL_write or ssl_real_impl (called by SSL_read) functions. I will try to find why and I will let you know. Thank you!

**Comment by qiushifengyu** [comment]
thank you very much! This is really strange，72_x86 is OK，if you find why please let me know why。thank you

**Comment by qiushifengyu** [comment]
Hello, I think i already find the problem。above chrome 72_x64，must hook chrome_child.dll，and it is child process。thanks
