### ISSUE TITLE
Chrome v45

### ISSUE THREAD

**Issue by olegsecurity** [NytroRST/NetRipper#3]
After update google chrome to version 45 there is no way to hook ssl_write() and ssl_read() functions.

**Comment by NytroRST** [comment]
Thank you, I will investigate as soon as possible!

**Comment by olegsecurity** [comment]
Thank you for your help, I found theese functions too. For SSL_Write() sequence=12, for SSL_Read() sequence=14, nBytesBeforeWrite  and nBytesBeforeRead must be 18.

**Comment by NytroRST** [comment]
Fixed.
