### ISSUE TITLE
Chrome version 

### ISSUE THREAD

**Issue by majidmetal** [NytroRST/NetRipper#4]
hi
netripper not work in chrome 48..
chrome crashed..
please help me to fix it...
thanks

**Comment by NytroRST** [comment]
Hi,

Yes, I saw this a 2-3 days ago, I will fix it as soon as possible.
It may be difficult to find the function signature yourself, so I have to look in the source code of Chrome and reverse it a bit to make sure I find the correct functions.

Thank you!

**Comment by majidmetal** [comment]
HI,
I need SSL Sniff Chrome last version for A project To my Company And Conference in University..
what time fix?!
Thank You very much....

**Comment by NytroRST** [comment]
Hi,

I have no idea. I am busy at work and I do not have too much free time in weekends, but as soon asI have some free time I will fix this.

For testing purposes, I think it should be fine to use an old version of Chrome.

Thanks!

**Comment by NytroRST** [comment]
Fixed.

**Comment by majidmetal** [comment]
HI
thanks For This release...
but One question..
when i sniff gmail in chrome with netripper not receive request https gmail..!!
worked with yahoo facebook and other website but not work with gmail and not receive my username and password gmail,,
Thanks for everything..

**Comment by NytroRST** [comment]
It may be HTTP 2.0, I am not sure.
No problem!
