### ISSUE TITLE
Chrome 50.0 support?

### ISSUE THREAD

**Issue by own2pwn** [NytroRST/NetRipper#5]
Hey, is there any way to fix chrome ssl in 50.0?
how can i fix sign\find it?

**Comment by alaiks77** [comment]
Me too, Hook SSL Chrome Doesn't work. 
(thanks)

**Comment by NytroRST** [comment]
I will look into this as soon as possible.

**Comment by jackalmeida** [comment]
Hi NytroRST,
Thanks for the great project you have done,  My partner is also romanian.  :)
Our company is working on a similar security project, We're very interested to work with you on a related project.
May i have you contact plz ?

**Comment by el-capitano** [comment]
Chrome always crashing even older version like 43
I've tested with Firefox it seems to be working but now for example with Nightly version of firefox verion 48 it's failing to inject, any fixes soon ?

**Comment by Numbers11** [comment]
This seems to be a maintained version of a Chrome hook:

https://github.com/WPO-Foundation/webpagetest/blob/499eb5f71ab0ca52587a8abfa9429c0c23543b55/agent/wpthook/hook_chrome_ssl.cc

However, in my chrome 61, the signature \x0\x0\x0\x3\x4\x3\x0\x0 was not present in the chrome.dll .rdata, maybe somebody more capable than me can figure out if it is outdated.

**Comment by NytroRST** [comment]
This method will not work anymore, since they removed the static data from the structure. Here is the new strucutre: https://cs.chromium.org/chromium/src/third_party/boringssl/src/ssl/internal.h?type=cs&q=ssl_protocol_method&l=2413

**Comment by NytroRST** [comment]
Added support for last Chrome on x64, I will close this issue.
