### ISSUE TITLE
Does not work on Internet Explorer

### ISSUE THREAD

**Issue by CaledoniaProject** [NytroRST/NetRipper#9]
I'm using Windows 7 x86 and IE 8.

I did some tests with HTTPS connections and non-HTTPS ones, here's the result ...

![screen 2017-10-09 at 15 41 48](https://user-images.githubusercontent.com/1357701/31328593-a0b93670-ac9b-11e7-9f87-60d85162f235.jpg)

I have three problems,
1. For HTTPS connections, I see some weird text, that looks like RAW HTTPS stream
2. For non-HTTPS connections, I tried to access `http://www.XXX.com/?user=123&pass=456`, it wasn't recorded
3. The `StringFinder` seems to record one-line only, am I wrong? See the "User-Agent" line

**Comment by NytroRST** [comment]
The "xxxx_iexplore_send.txt" file will contain only HTTP (not HTTPS data).
There should be a "xxx_iexplore_SslEncryptPacket.txt" file if everything is fine, but I also had some issues with Internet Explorer. 
I will take a look as soon as possible.
Thank you!
